stages:
  # - build
  - deploy

.for_release:
  environment:
    name: release
  variables:
    DOCKER_IMAGE_TAG: stable
    NAMESPACE: zetabot-production
  only:
    - master

.for_development:
  environment:
    name: development
  variables:
    DOCKER_IMAGE_TAG: latest
    NAMESPACE: zetabot-staging
  only:
    - develop

.build:
  stage: build
  image: ${CI_REGISTRY}/pub/docker-images:docker20-stable
  services:
    - docker:20-dind
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker pull ${CI_REGISTRY_IMAGE}:${DOCKER_IMAGE_TAG} || true
      .
    - docker build
      --cache-from ${CI_REGISTRY_IMAGE}:${DOCKER_IMAGE_TAG}
      --tag ${CI_REGISTRY_IMAGE}:${DOCKER_IMAGE_TAG}
      --label org.label-schema.schema-version="1.0"
      --label org.label-schema.vcs-url="${CI_PROJECT_URL}.git"
      --label org.label-schema.vcs-ref="${CI_COMMIT_SHA}"
      .
    - docker push ${CI_REGISTRY_IMAGE}:${DOCKER_IMAGE_TAG}

.deploy:
  stage: deploy
  image: ${CI_REGISTRY}/pub/docker-images:eks-stable
  script:
    # Authenticate using the service account
    - mkdir -p ~/.aws
    - echo $AWS_KEY | base64 --decode -i > ~/.aws/credentials
    - echo ~/.aws/credentials
    - aws eks update-kubeconfig --region ap-southeast-1 --name imp
    - kubectl rollout restart -n $NAMESPACE deployment/zetabot-blog

# development:publish:
#   extends:
#     - .for_development
#     - .build

development:deploy:
  extends:
    - .for_development
    - .deploy

# release:publish:
#   extends:
#     - .for_release
#     - .build

release:deploy:
  extends:
    - .for_release
    - .deploy